# Generated by Django 5.1.2 on 2025-01-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DistMatrix_fort_lat_long',
            fields=[
                ('matrix_fort_id', models.AutoField(primary_key=True, serialize=False)),
                ('matrix_fort_name', models.CharField(max_length=100)),
                ('matrix_fort_district', models.CharField(max_length=100)),
                ('matrix_fort_latitude', models.FloatField(blank=True, null=True)),
                ('matrix_fort_longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['matrix_fort_id'],
            },
        ),
        migrations.CreateModel(
            name='Forts',
            fields=[
                ('fort_id', models.AutoField(primary_key=True, serialize=False)),
                ('fort_name', models.CharField(max_length=100)),
                ('fort_district', models.CharField(max_length=100)),
                ('fort_latitude', models.FloatField(blank=True, null=True)),
                ('fort_longitude', models.FloatField(blank=True, null=True)),
                ('link', models.URLField()),
                ('fort_image', models.ImageField(blank=True, null=True, upload_to='img/fort_images/')),
            ],
            options={
                'ordering': ['fort_id'],
            },
        ),
        migrations.CreateModel(
            name='latitude_longitude',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('origin_latitude', models.FloatField(blank=True, null=True)),
                ('origin_longitude', models.FloatField(blank=True, null=True)),
                ('destination_latitude', models.FloatField(blank=True, null=True)),
                ('destination_longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_lat_lon', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['plan_id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('origin_addresses', models.CharField(max_length=500)),
                ('destination_addresses', models.CharField(max_length=500)),
                ('mode', models.CharField(max_length=50)),
                ('traffic_model', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('distance_value', models.IntegerField()),
                ('distance_text', models.CharField(max_length=50)),
                ('duration_value', models.IntegerField()),
                ('duration_text', models.CharField(max_length=50)),
                ('duration_in_traffic_value', models.IntegerField()),
                ('duration_in_traffic_text', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_result', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=50)),
                ('traffic_model', models.CharField(max_length=50)),
                ('departure_time', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_route', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
