# Generated by Django 5.1.2 on 2025-01-26 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='all_recommendations',
            fields=[
                ('recommendation_id', models.AutoField(primary_key=True, serialize=False)),
                ('recom_district', models.CharField(blank=True, max_length=50, null=True)),
                ('recom_forts', models.CharField(blank=True, max_length=500, null=True)),
                ('recom_title', models.CharField(blank=True, max_length=200, null=True)),
                ('recom_details', models.TextField(blank=True, null=True)),
                ('image_name', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='all_trips',
            fields=[
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_district', models.CharField(blank=True, max_length=100, null=True)),
                ('forts_visited', models.CharField(blank=True, max_length=1000, null=True)),
                ('required_time', models.CharField(blank=True, max_length=100, null=True)),
                ('minimum_cost', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
